#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/gemstone

PRODUCT_COPY_FILES += \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Bluetooth_cal.acdb \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_General_cal.acdb \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Global_cal.acdb \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Handset_cal.acdb \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Hdmi_cal.acdb \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Headset_cal.acdb \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Speaker_cal.acdb \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_workspaceFile.qwsp \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.2.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.2.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/LDC_packdata_xiaomi_M17_Ofilm_3264x2448_20220608.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi_M17_Ofilm_3264x2448_20220608.dat \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/LDC_packdata_xiaomi_M17_Sunny_3264x2448_20220707.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi_M17_Sunny_3264x2448_20220707.dat \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/aivsParams:$(TARGET_COPY_OUT_VENDOR)/etc/camera/aivsParams \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/aivsParams2:$(TARGET_COPY_OUT_VENDOR)/etc/camera/aivsParams2 \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/dualcam_bokeh_params.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dualcam_bokeh_params.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/golden_aac_s5kjn1_wide_ii.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_aac_s5kjn1_wide_ii.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/golden_ofilm_ov48b2q_wide_i.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_ofilm_ov48b2q_wide_i.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/golden_sunny_s5kjn1_wide_i.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_sunny_s5kjn1_wide_i.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/libalfpc_tuning_20181222.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/libalfpc_tuning_20181222.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/model_back.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_back.dlc \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/model_front.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_front.dlc \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_aac_ov02b10_macro_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_aac_ov02b10_macro_i.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_aac_s5k3l6_front_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_aac_s5k3l6_front_i.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_qtech_s5k3l6_front_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_qtech_s5k3l6_front_ii.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_ov08d10_ultra_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_ov08d10_ultra_i.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i_10x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i_10x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i_2x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i_2x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i_4x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i_4x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i_6x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i_6x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i_8x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5kjn1_wide_i_8x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5k3l6_front_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5k3l6_front_i.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii_10x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii_10x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii_2x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii_2x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii_4x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii_4x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii_6x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii_6x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii_8x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5kjn1_wide_ii_8x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_ov08d10_front_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_ov08d10_front_ii.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_ov08d10_ultra_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_ov08d10_ultra_ii.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i_10x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i_10x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i_2x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i_2x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i_4x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i_4x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i_6x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i_6x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i_8x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_ov48b2q_wide_i_8x.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_qtech_s5k3l6_front_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_qtech_s5k3l6_front_ii.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_sunny_ov08d10_front_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_sunny_ov08d10_front_i.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/morpho_lowlight_2.0_sunny_sc202cs_macro_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_sunny_sc202cs_macro_ii.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/vidhance_kernel1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_kernel1.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/camera/vidhance_kernel2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_kernel2.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/init/init.batterysecret.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.batterysecret.rc \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/libnfc-hal-st.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-hal-st.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/moonstone_qrd_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/moonstone_qrd_ak991x_0.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/moonstone_qrd_ak991x_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/moonstone_qrd_ak991x_1.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/moonstone_qrd_bmi3x0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/moonstone_qrd_bmi3x0.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/moonstone_qrd_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/moonstone_qrd_icm4x6xx_0.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/moonstone_qrd_qmc630x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/moonstone_qrd_qmc630x_0.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/moonstone_qrd_qmc630x_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/moonstone_qrd_qmc630x_1.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/moonstone_qrd_sar_algo_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/moonstone_qrd_sar_algo_1.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/moonstone_qrd_sx933x.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/moonstone_qrd_sx933x.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/moonstone_qrd_tmd2755.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/moonstone_qrd_tmd2755.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_aod.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aod.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_ccd_v2_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_walk.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_ccd_v3_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_walk.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_direct_channel.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/strait_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_bu52053nvx_0.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/strait_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_default_sensors.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/strait_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_dynamic_sensors.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/strait_icp101xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_icp101xx_0.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/strait_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_power_0.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/strait_qrd_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_qrd_lsm6dst_0.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/strait_qrd_tmd2725.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_qrd_tmd2725.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/config/strait_tmd2725.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_tmd2725.json \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-arvr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-arvr.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-chg-only.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-chg-only.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-class0.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-map-india.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map-india.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-mgame.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-nolimits.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-normal-india.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal-india.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-phone.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-region-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-region-map.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-video.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermal-youtube.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-youtube.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/gemstone/proprietary/vendor/firmware/focaltech_mp_fw_sdc.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_mp_fw_sdc.ini \
    vendor/xiaomi/gemstone/proprietary/vendor/firmware/focaltech_ts_fw_.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/firmware/focaltech_ts_fw_sdc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_sdc.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/firmware/sipa.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sipa.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/firmware/st21nfc_conf.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/st21nfc_conf.txt \
    vendor/xiaomi/gemstone/proprietary/vendor/firmware/st21nfc_fw7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st21nfc_fw7.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_aac_ov02b10_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_aac_ov02b10_macro.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_aac_s5k3l6_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_aac_s5k3l6_front.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_aac_s5kjn1_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_aac_s5kjn1_wide.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_aac_sc202cs_depth.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_aac_sc202cs_depth.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_ofilm_ov08d10_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_ofilm_ov08d10_front.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_ofilm_ov08d10_ultra.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_ofilm_ov08d10_ultra.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_oflim_ov48b2q_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_oflim_ov48b2q_wide.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_qtech_s5k3l6_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_qtech_s5k3l6_front.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_sunny_ov08d10_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_sunny_ov08d10_front.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_sunny_ov08d10_ultra.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_sunny_ov08d10_ultra.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_sunny_s5kjn1_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_sunny_s5kjn1_wide.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.sensormodule.m17_sunny_sc202cs_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.m17_sunny_sc202cs_macro.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_aac_ov02b10_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_aac_ov02b10_macro.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_aac_s5k3l6_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_aac_s5k3l6_front.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_aac_s5kjn1_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_aac_s5kjn1_wide.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_aac_sc202cs_depth.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_aac_sc202cs_depth.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_ofilm_ov08d10_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_ofilm_ov08d10_front.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_ofilm_ov08d10_ultra.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_ofilm_ov08d10_ultra.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_oflim_ov48b2q_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_oflim_ov48b2q_wide.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_qtech_s5k3l6_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_qtech_s5k3l6_front.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_sunny_ov08d10_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_sunny_ov08d10_front.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_sunny_ov08d10_ultra.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_sunny_ov08d10_ultra.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_sunny_s5kjn1_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_sunny_s5kjn1_wide.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/com.qti.tuned.m17_sunny_sc202cs_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.m17_sunny_sc202cs_macro.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/xiaomi/gemstone/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    libcamxexternalformatutils \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libaudcal \
    com.qti.flash.ktd2691 \
    com.qti.sensor.m17_aac_ov02b10_macro \
    com.qti.sensor.m17_aac_s5k3l6_front \
    com.qti.sensor.m17_aac_s5kjn1_wide \
    com.qti.sensor.m17_aac_sc202cs_depth \
    com.qti.sensor.m17_ofilm_ov08d10_front \
    com.qti.sensor.m17_ofilm_ov08d10_ultra \
    com.qti.sensor.m17_ofilm_ov48b2q_wide \
    com.qti.sensor.m17_qtech_s5k3l6_front \
    com.qti.sensor.m17_sunny_ov08d10_front \
    com.qti.sensor.m17_sunny_ov08d10_ultra \
    com.qti.sensor.m17_sunny_s5kjn1_wide \
    com.qti.sensor.m17_sunny_sc202cs_macro \
    com.arcsoft.node.realtimebokeh \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.mialgocontrol \
    com.qti.node.mimovie \
    com.qti.node.ml \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.vidhance.node.processing \
    libdepthmapwrapper_secure \
    com.qti.chiusecaseselector \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.mannar \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.settings.mannar \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom \
    com.qti.chi.override \
    fingerprint.fpc.default \
    fingerprint.goodix.default \
    libHalSuperSensorServer \
    libSNPE \
    libSnpeHtpPrepare \
    libSnpeHtpV68Stub \
    libSnpeHtpV69Stub \
    libSuperSensor \
    libSuperSensorCPU \
    libaidenoiser \
    libaidenoiserv2 \
    libalCFR \
    libalLDC \
    libalhLDC \
    libarcsoft_beautyshot \
    libarcsoft_calibverify_TriCamera \
    libarcsoft_dualcam_refocus_image \
    libarcsoft_dualcam_refocus_video \
    libarcsoft_hdr_detection \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_single_chart_calibration \
    libarcsoft_supernight \
    libarcsoft_tricam_calibration \
    libarcsoft_tricam_verification \
    libbitmlengine \
    libbitmlenginev2 \
    libc++_shared \
    libc++_shared_vf \
    libcamera_nn_stub \
    libcamera_scene \
    libcamerapostproc \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchilog \
    libcom.qti.chinodeutils \
    libgf_ca \
    libgf_hal \
    libgoodixhwfingerprint \
    libipebpsstriping \
    libipebpsstriping170 \
    libjpege \
    libmctfengine_stub \
    libmfec \
    libmialgo_ai_vision \
    libmialgo_aio_seg \
    libmialgo_sd \
    libmialgo_utils \
    libmialgoengine \
    libmiphone_capture_bokeh \
    libmmcamera_bestats \
    libmmcamera_cac3 \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmorpho_Lowlight \
    libmpbase \
    libofflinedump \
    libofflinelog \
    libopencv \
    libopestriping \
    libos \
    libpowercore \
    libqll10 \
    libqllengine \
    libremosaic_wrapper \
    libremosaiclib \
    librmsclib1 \
    libsnpe_dsp_domains_v2 \
    libswregistrationalgo \
    libsynx \
    libtfestriping \
    libthreadutils \
    libvideofilter_only \
    libvideooptfeature \
    libvidhance \
    libvidhance_ldc \
    libvidhance_stabilizer \
    sensors.ssc \
    sensors.touch.detect \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor_lib_rfsa_adsp_capi_v2_aptX_CLHDAD_Encoder_so \
    vendor_lib_rfsa_adsp_capi_v2_aptX_CLHDAD_Speech_Decoder_so \
    vendor_lib_rfsa_adsp_libSnpeHtpV68Skel_so \
    vendor_lib_rfsa_adsp_libSnpeHtpV69Skel_so \
    vendor_lib_rfsa_adsp_libadsp_jpege_skel_so \
    vendor_lib_rfsa_adsp_libapps_mem_heap_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_skel_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_v2_skel_so \
    vendor_lib_rfsa_adsp_libcalculator_skel_so \
    vendor_lib_rfsa_adsp_libcamera_nn_skel_so \
    vendor_lib_rfsa_adsp_libdspCV_skel_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_binning_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_so \
    vendor_lib_rfsa_adsp_libfastcvdsp_skel_so \
    vendor_lib_rfsa_adsp_libhdr_skel_so \
    vendor_lib_rfsa_adsp_libmctfengine_skel_so \
    vendor_lib_rfsa_adsp_libscveObjectSegmentation_skel_so \
    vendor_lib_rfsa_adsp_libscveT2T_skel_so \
    vendor_lib_rfsa_adsp_libsnpe_dsp_v65_domains_v2_skel_so \
    vendor_lib_rfsa_adsp_libsnpe_dsp_v66_domains_v2_skel_so \
    vendor_lib_rfsa_adsp_libsns_device_mode_skel_so \
    vendor_lib_rfsa_adsp_libsns_low_lat_stream_skel_so \
    vendor_lib_rfsa_adsp_misound_karaoke_res_bin \
    vendor_lib_rfsa_adsp_misound_karaokemix_res_bin \
    vendor_lib_rfsa_adsp_misound_res_bin \
    vendor_lib_rfsa_adsp_misound_res_headphone_bin \
    batterysecret
